baseURL = "https://gotopchuang.github.io/"
languageCode = "zh-tw"
title = "Gotop Chuang 莊向峰"

enableGitInfo = false

[params]
BookMenuBundle = '/menu'

[markup.goldmark.renderer]
unsafe= true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5